### ISSUE TITLE
SPIKE: Research DBs

### ISSUE THREAD

**Issue by JingusJohn** [CamJak/Boss-Integrated-Scheduler#4]
We need to look into what database system we'd like to use. SQL is familiar, but there are other options.

If we go with SQL, which flavor are we going to use? (PostgreSQL, MySQL, SQLServer, etc.)

We definitely want to go with something free.

Another thing to consider is how we'd actually interact with the database.

**Comment by jackjohn7** [comment]
Yeah we'd have to host it somewhere, but it might be simplest to just go with a normal server host like digital ocean and just hosting a postgres server.

We're needing to track sections that relate to courses that relate to subjects, so a relational database seems to be the most sensible.

**Comment by jackjohn7** [comment]
PocketBase is an open source backend. It has SQLite as its database and it has authentication built in. It is very easy to use with front end frameworks like Svelte. More info here: https://pocketbase.io/ 
SurrealDB is an interesting bleeding edge candidate. PostgreSQL is a safe option. However, with either option, we still have to actually make the backend ourselves.

**Comment by jackjohn7** [comment]
Our database needs should be simple enough where a SQL database, specifically PostgreSQL, will meet our needs adequately. Our database is being hosted on Railway at the moment.
